base: &base
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *base
  database: art_development

test:
  <<: *base
  database: art_test
  username: jenniferart
  password: password
  host: localhost
  port: 5432

production:
  <<: *base
  database: art_production
  username: art
  password: <%= ENV['ART_DATABASE_PASSWORD'] %>
