name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: foo
          POSTGRES_PASSWORD: bar
          POSTGRES_DB: baz
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - name: Build and test with Rake
      run: |
        sudo apt-get install libpq-dev
        pg_ctl -D /usr/local/var/postgres start
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
